version: '4'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  web:
    image: api
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/admin
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data:
