version: '4'

services:
  web:
    build:
      context: .
    volumes:
      - ./admin:/admin
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000

    db:
      image: postgres:16.1
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=${SQL_DATABASE}
        - POSTGRES_USER=${SQL_USER}
        - POSTGRES_PASSWORD=${SQL_PASSWORD}
